assets:
  log_file: log/development.log
  scene_file: scene/scene_full.yml

  glfw_swap_interval: 1
  gl_debug: true
  gl_no_error: false

  resolution_scale: 0.5
  gbuffer_scale: 0.5
  buffer_scale: 1.0

  camera_move_mormal: [5.5, 7.5, 7.5]
  camera_move_run: [10, 14, 14]
  camera_rotate_normal: [18, 18, 18]
  camera_rotate_run: [56, 56, 56]
  camera_zoom_normal: [20, 20, 20]
  camera_zoom_run: [25, 25, 25]
  camera_mouse_senstivity: [0.1, 0.1, 0.5]

  async_loader_enabled: true
  async_loader_delay: 0

  models_dir: 3d_model
  shaders_dir: shader
  sprites_dir: sprites
  textures_dir: textures

  placeholder_texture_always: false
  placeholder_texture: textures/tiles_1024.png

  use_imgui: false

  use_script: true
  use_light: true

  force_wireframe: false

  render_cube_map: true
  render_shadow_map: true
  render_mirror_map: true
  render_water_map: true

  show_normals: false
  show_rear_view: false
  show_shadow_map_view: false
  show_reflection_view: false
  show_refraction_view: false
  show_objectid_view: false

  show_volume: true
  show_selection_volume: true
  show_highlight: true
  show_selection: true
  show_cube_map_center: false
  show_tagged: false

  rasterizer_discard: false

  debug_clear_color: true
  clear_color: true

  frustum_enabled: true
  frustum_cpu: true
  frustum_gpu: false
  frustum_debug: true
  frustum_visual: false

  camera_fov: 45

  render_frame_start: 1
  render_frame_step: 1

  mirror_render_frame_start: 0
  mirror_render_frame_step: 3

  mirror_fov: 30

  water_tile_size: 100
  water_render_frame_start: 0
  water_render_frame_step: 1

  terrain_grid_size: 64

  batch_size: 500
  batch_buffers: 500
  batch_debug: true

  draw_debug: false

  near_plane: 0.1
  far_plane: 2000.0

  fog_color: [0.2, 0.2, 0.2, 1.0]
  fog_start: 500.0
  fog_end: 2000.0
  fog_density: 1.1

  shadow_planes: [0.1, 30, 100, 500]
  xxshadow_planes: [0.1, 20, 100]
  xxshadow_planes: [0.1, 100]
  shadow_map_sizes: [2048, 2048, 2048, 1024]
  shadow_render_frame_start: 0
  shadow_render_frame_step: 1

  mirror_reflection_size: 1024
  mirror_refraction_size: 1024

  water_reflection_size: 1024
  water_refraction_size: 1024

  cube_map_size: 1024
  cube_map_near_plane: 0.5
  cube_map_far_plane: 200
  cube_map_render_frame_start: 1
  cube_map_render_frame_step: 2

  viewport_effect_enabled: true
  viewport_effect: none

  compute_groups: [32, 1, 1]
