assets:
  log_file: log/development.log
  scene_file: scene_physics.yml
  scene_file: scene_text.yml

  glfw_swap_interval: 1
  gl_debug: true
  gl_no_error: false
  gl_use_mapped: false
  gl_use_invalidate: true
  gl_use_fence: false
  gl_use_single_fence: false
  gl_use_debug_fence: false
  gl_use_finish: false

  prepass_depth_enabled: false

  g_buffer_scale: 0.5
  water_reflection_buffer_scale: 0.125
  water_refraction_buffer_scale: 0.25
  mirror_reflection_buffer_scale: 0.25

  window_size: [800, 600]
  window_maximized: true
  window_full_screen: false

  camera_move_mormal: [5.5, 7.5, 7.5]
  camera_move_run: [10, 14, 14]
  camera_rotate_normal: [18, 18, 18]
  camera_rotate_run: [56, 56, 56]
  camera_zoom_normal: [20, 20, 20]
  camera_zoom_run: [25, 25, 25]
  camera_mouse_senstivity: [0.1, 0.1, 0.5]

  async_loader_enabled: true
  async_loader_delay: 0

  assets_dir: resources/assets
  shaders_dir: shader

  placeholder_texture_always: false
  placeholder_texture: textures/tiles_1024.png

  use_imgui: false

  use_script: true
  use_light: true

  force_wireframe: false

  show_normals: false
  show_rear_view: false
  show_shadow_map_view: false
  show_reflection_view: false
  show_refraction_view: false
  show_objectid_view: false

  show_volume: true
  show_selection_volume: true
  show_highlight: true
  show_selection: true
  show_cube_map_center: false
  show_tagged: false

  rasterizer_discard: false

  use_debug_color: true

  frustum_enabled: true
  frustum_cpu: true
  frustum_gpu: false
  frustum_debug: true
  frustum_visual: false

  camera_fov: 45

  render_frame_start: 1
  render_frame_step: 1

  mirror_map_enabled: true
  mirror_reflection_size: 2048
  mirror_fov: 30
  mirror_render_mirror: true
  mirror_render_water: true
  mirror_render_frame_start: 0
  mirror_render_frame_step: 4
  mirror_map_near_plane: 0.1
  mirror_map_far_plane: 600

  water_map_enabled: true
  water_tile_size: 100
  water_render_frame_start: 0
  water_render_frame_step: 1
  water_map_near_plane: 0.1
  water_map_far_plane: 500

  terrain_grid_size: 64

  batch_size: 1000
  batch_buffers: 300
  batch_debug: false

  draw_debug: false

  near_plane: 0.1
  far_plane: 2000.0

  fog_color: [0.2, 0.2, 0.2, 1.0]
  fog_start: 500.0
  fog_end: 2000.0
  fog_density: 1.1

  shadow_map_enabled: true

  shadow_polygon_offset_enabled: true
  shadow_polygon_offset: [2, 0.5]
  shadow_planes: [0.1, 30, 120, 500]
  xxshadow_planes: [0.1, 20, 100]
  xxshadow_planes: [0.1, 100]
  shadow_map_sizes: [1024, 1024, 1024, 1024]
  shadow_render_frame_start: 0
  shadow_render_frame_step: 1

  cube_map_enabled: true
  cube_map_seamless: true
  cube_map_skip_others: true
  cube_map_size: 512
  cube_map_near_plane: 0.5
  cube_map_far_plane: 200
  cube_map_render_mirror: true
  cube_map_render_water: true
  cube_map_render_frame_start: 1
  cube_map_render_frame_step: 6

  skybox_enabled: true
  skybox_size: 1024

  environment_map_enabled: true
  environment_map_size: 512
  irradiance_map_size: 32
  prefilter_map_size: 128
  brdf_lut_size: 512

  viewport_effect_enabled: true
  viewport_effect: none

  hdr_gamma: 2.2
  hdr_exposure: 1.0

  effect_bloom_enabled: false
  effect_bloom_exposure: 1.0
  effect_bloom_iterations: 1

  effect_oit_enabled: true
  effect_glow_enabled: true
  effect_fog_enabled: true

  compute_groups: [32, 1, 1]
