assets:
  log_file: log/development.log
  scene_file: scene/scene_lucy.yml

  glfw_swap_interval: 3
  gl_debug: true
  gl_no_error: false

  resolution_scale: 0.5

  async_loader_enabled: true
  async_loader_delay: 10

  models_dir: 3d_model
  shaders_dir: shader/test6
  sprites_dir: sprites
  textures_dir: textures
  ground_offset: [200, 0, 200]

  placeholder_texture_always: false
  placeholder_texture: textures/tiles_1024.png

  ground_offset_nope: [0.0, 15.0, -40.0]
  xxground_offset: [200, 0, 200]

  use_imgui: false
  use_light: true
  use_wireframe: false

  show_normals: false
  show_rear_view: false
  show_shadow_map_view: false
  show_reflection_view: false
  show_refraction_view: false
  show_objectid_view: false

  show_volume: true
  show_selection_volume: true
  show_highlight: true
  show_selection: true
  show_cube_map_center: true
  show_tagged: true

  rasterizer_discard: false

  debug_clear_color: true
  clear_color: true

  frustum_enabled: true
  frustum_debug: true

  camera_fov: 45

  render_frame_start: 1
  render_frame_step: 1

  mirror_render_frame_start: 0
  mirror_render_frame_step: 2

  mirror_fov: 30

  water_tile_size: 100
  water_render_frame_start: 0
  water_render_frame_step: 2

  terrain_vertex_count: 32
  terrain_tile_size: 400

  batch_size: 2048
  batch_buffers: 8

  near_plane: 0.1
  far_plane: 1000.0

  fog_color: [0.1, 0.1, 0.2, 1.0]
  fog_start: 50.0
  fog_end: 700.0

  shadow_near_plane: 0.1
  shadow_far_plane: 1000.0
  shadow_frustum_size: 200
  shadow_map_size: 1024
  shadow_render_frame_start: 0
  shadow_render_frame_step: 2

  mirror_reflection_size: 1000
  mirror_rdRefraction_size: 1000

  water_reflection_size: 1000
  water_refraction_size: 1000

  cube_map_size: 1000
  cube_map_near_plane: 0.5
  cube_map_far_plane: 200
  cube_map_render_frame_start: 1
  cube_map_render_frame_step: 2

  viewport_effect: none
