assets:
  log_file: log/development.log
  #scene_file: physics.yml
  #scene_file: full.yml
  #scene_file: particle.yml

  glfw_swap_interval: 1
  gl_debug: true
  gl_no_error: false
  gl_use_mapped: false
  gl_use_invalidate: true
  gl_use_fence: false
  #gl_use_single_fence: false
  gl_use_fence_debug: false
  gl_use_finish: false

  glsl_use_debug: true

  target_frame_rate: 30

  compressed_textures_enabled: true
  prepass_depth_enabled: false

  g_buffer_scale: 0.5

  window_icon: textures/kari_512.png
  window_size: [800, 600]
  window_maximized: true
  window_full_screen: false

  camera_move_mormal: [2.5, 2.5, 2.5]
  camera_move_run: [8, 8, 8]
  camera_rotate_normal: [28, 28, 28]
  camera_rotate_run: [56, 56, 56]
  camera_zoom_normal: [20, 20, 20]
  camera_zoom_run: [25, 25, 25]
  camera_mouse_senstivity: [0.1, 0.1, 0.5]

  async_loader_enabled: true
  async_loader_delay: 0

  assimp_importer_enabled: true
  assimp_debug: false

  assets_dir: resources/assets
  assets_build_dir: resources/build/1024
  shaders_dir: shader

  placeholder_texture_always: false
  placeholder_texture: textures/tiles_1024_color.png

  use_editor: true
  editor_font_size: 18
  editor_font_path: fonts/Vera.ttf
  #editor_imgui_demo: false

  use_script: true

  #force_line_mode: false

  #show_normals: false
  show_rear_view: false
  show_shadow_map_view: false
  #show_reflection_view: false
  #show_refraction_view: false
  #show_objectid_view: false

  show_volume: false
  show_selection_volume: false
  show_environment_probe: false

  show_highlight: true
  show_selection: true
  show_tagged: false

  rasterizer_discard: false

  use_debug_color: true

  use_lod_debug: false

  frustum_enabled: true
  frustum_cpu: true
  frustum_gpu: false
  frustum_parallel_limit: 500
  frustum_debug: true

  camera_fov: 45

  render_frame_start: 1
  render_frame_step: 1

  terrain_grid_size: 64

  batch_size: 1000
  batch_buffers: 64
  batch_debug: false

  draw_debug: false

  node_registry_debug: false
  node_registry_defer_sort: true

  near_plane: 0.1
  far_plane: 2000.0

  fog_color: [0.2, 0.2, 0.2, 1.0]
  fog_start: 500.0
  fog_end: 2000.0
  fog_density: 1.1

  animation_enabled: true
  animation_node_tree: true
  animation_first_frame_only: false
  animation_once_only: false
  animation_max_count: 1000

  physics_enabled: true
  physics_update_enabled: true
  physics_initial_delay: 3
  physics_show_objects: true

  physics_dContactMu2: false
  physics_dContactSlip1: true
  physics_dContactSlip2: true
  physics_dContactRolling: false
  physics_dContactBounce: true
  physics_dContactMotion1: false
  physics_dContactMotion2: false
  physics_dContactMotionN: false
  physics_dContactSoftCFM: true
  physics_dContactSoftERP: true
  physics_dContactApprox1: true
  physics_dContactFDir1: false

  physics_mu: 100
  physics_mu2: 0
  physics_rho: 0
  physics_rho2: 0
  physics_rhoN: 0
  physics_slip1: 0.7
  physics_slip2: 0.7
  physics_bounce: 0.1
  physics_bounce_vel: 1.1
  physics_motion1: 0
  physics_motion2: 0
  physics_motionN: 0
  physics_soft_erp: 0.9
  physics_soft_cfm: 0.9

  light_enabled: true
  normal_map_enabled: true

  parallax_enabled: true
  parallax_depth: 0.0
  parallax_method: 1
  parallax_debug_enabled: false
  parallax_debug_depth: 0.01

  particle_enabled: true
  particle_max_count: 1000000

  decal_enabled: true
  decal_max_count: 4000

  shadow_map_enabled: true

  shadow_polygon_offset_enabled: true
  shadow_polygon_offset: [2, 0.5]
  xshadow_planes: [0.1, 25, 75, 150, 500]
  xshadow_map_sizes: [1024, 1024, 1024, 1024]
  shadow_planes: [0.1, 40, 90, 250]
  shadow_map_sizes: [2048, 1024, 1024]
  shadow_render_frame_start: 0
  shadow_render_frame_step: 1
  shadow_visual: false

  mirror_map_enabled: true
  mirror_map_fov: 30
  mirror_map_reflection_buffer_scale: 0.25
  mirror_map_render_mirror: true
  mirror_map_render_water: true
  mirror_map_render_frame_start: 0
  mirror_map_render_frame_step: 2
  mirror_map_near_plane: 0.1
  mirror_map_far_plane: 600

  water_map_enabled: true
  water_map_reflection_buffer_scale: 0.125
  water_map_refraction_buffer_scale: 0.25
  water_map_tile_size: 100
  water_map_render_frame_start: 0
  water_map_render_frame_step: 1
  water_map_near_plane: 0.1
  water_map_far_plane: 600

  cube_map_enabled: true
  cube_map_buffer_scale: 0.5
  cube_map_seamless: true
  cube_map_skip_others: true
  cube_map_size: 512
  cube_map_near_plane: 0.5
  cube_map_far_plane: 200
  cube_map_render_mirror: true
  cube_map_render_water: true
  cube_map_render_frame_start: 1
  cube_map_render_frame_step: 6

  skybox_enabled: true
  skybox_color_enabled: false
  skybox_color: [1, 0, 1]
  skybox_size: 1024

  environment_map_enabled: true
  environment_map_size: 512
  irradiance_map_size: 128
  prefilter_map_size: 256
  brdf_lut_size: 512

  layers:
    - name: main
      order: 50
      enabled: true
      effect_enabled: false
      effect: none
      blend_enabled: false
      blend_factor: 1.0
    - name: rear
      order: 75
      enabled: false
      effect_enabled: false
      effect: none
      blend_enabled: false
      blend_factor: 0.95
    - name: player
      order: 100
      enabled: true
      effect_enabled: false
      effect: none
      blend_enabled: true
      blend_factor: 0.99
    - name: ui
      order: 150
      enabled: true
      effect_enabled: false
      effect: none
      blend_enabled: true
      blend_factor: 0.95

  gamma_correct_enabled: true
  hardware_gamma_correct_enabled: true
  gamma_correct: 2.2

  hdr_tone_mapping_enabled: true
  hdr_exposure: 1.0

  effect_bloom_enabled: true
  effect_bloom_threshold: 5.0

  effect_oit_enabled: true
  effect_oit_min_blend_threshold: 0.001
  effect_oit_max_blend_threshold: 0.995

  effect_ssao_enabled: true
  effect_ssao_base_color_enabled: false
  effect_ssao_base_color: [0.9, 0.9, 0.9]

  effect_emission_enabled: true
  effect_fog_enabled: true

  compute_groups: [32, 1, 1]
