---
name: Full
viewports:
skybox:
  shader: skybox
  material: skybox
lights: {}
root:
  id: 50733c80-df4e-47ab-9596-ccfadb1805d8
  type: origo
  pos: [200, 0, 200]
  rotation: [0, 0, 0]
  enabled: true
  controller:
    type: path
    mode: 1
    enabled: false
entities:
  - name: Origo
    type: origo
    pos: [0, 0, -5]
    camera:
      zoom: 45
      up: [0, 1, 0]
      front: [0, 0, -1]
      pos: [200, 0, 190]
      rotation: [0, 180, 0.0]
      enabled: true
    controller:
      type: camera
      enabled: true
    enabled: true
  - name: Silver ball
    model: water_ball
    material: silver_ball
    force_material: true
    shader: texture
    pos: [0, 1, 0]
    scale: 1.3
    material_modifier:
      reflection: 0.05
    enabled: true
  - name: Woodcube
    model: texture_cube
    shader: texture
    material: woodwall
    force_material: true
    pos: [5.0, 5.0, 5.0]
    scale: 1
    enabled: true
  - name: Four cubes
    model: texture_cube
    shader: texture
    scale: 1
    enabled: true
    clones:
      - pos: [-5.0, 0.0, -5.0]
      - pos: [5.0, 0.0, -5.0]
      - pos: [-5.0, 0.0, 5.0]
      - pos: [5.0, 0.0, 5.0]
  - name: Skeleton army
    type: sprite
    shader: sprite
    pos: [15, 6.5, 20.0]
    material: skeleton
    batch_size: 1000
    render_flags:
      alpha: true
      render_back: true
    scale: [1.5, 3, 1]
    repeat:
      x_count: 10
      z_count: 101
      x_step: -4
      z_step: 1.5
    enabled: true
  - name: Cube map 1
    type: origo
    pos: [0.0, -3.0, 0.0]
    render_flags:
      cube_map: true
    enabled: false
  - name: Glass ball
    model: glass_ball
    shader: texture
    pos: [5.0, 20.0, 0.0]
    scale: 1.3
    material_modifier:
      reflection: 0.1
      refraction: 0.9
      refraction_ratio: [1.0, 1.52]
    enabled: false
  - name: Brick wall
    type: quad
    material: brickwall
    shader: texture
    pos: [-5.0, 8.5, 14.0]
    render_flags:
      render_back: true
    repeat:
      x_count: 3
      x_step: 4
    enabled: false
  - name: Wood wall
    type: quad
    material: woodwall
    shader: texture
    pos: [-3.0, 8.5, 14.0]
    render_flags:
      render_back: true
    repeat:
      x_count: 2
      x_step: 4
    enabled: false
  - name: Giant wooden box
    id: e264f27f-d949-4504-b862-583213484d7c
    type: quad
    xmodel: woodwall
    material: giant_woodbox
    shader: texture
    clone_position: [0, 40, 0]
    render_flags:
      render_back: true
      no_shadow: true
    scale: [100, 100, 100]
    enabled: false
    clones:
      - pos: [0.0, 100.0, 0.0]
        rot: [270, 0, 0]
        id: 9da42971-4809-480b-98b6-ed238b978ed2
      - pos: [0.0, -100.0, .0]
        rot: [90, 0, 0]
      - pos: [100.0, 0.0, 0.0]
        rot: [0, 90, 0]
      - pos: [-100.0, 0.0, 0.0]
        rot: [0, 270, 0]
      - pos: [0.0, 0.0, 100.0]
        rot: [0, 0, 0]
      - pos: [0.0, 0.0, -100.0]
        rot: [0, 180, 0]
  - name: Big mirror 1
    type: quad
    material: mirror
    shader: mirror
    pos: [-40.0, 10.0, 10.0]
    rotation: [0.0, 90.0, 0.0]
    scale: 15.0
    render_flags:
      render_back: true
      mirror: true
      no_reflect: true
      no_refract: true
    plane_normal: [0.0, 0.0, 1.0]
    enabled: true
materials:
  - name: skybox
    type: skybox
    asset: skybox
  - name: silver_ball
    ns: 51.2
    ka: [0.1923, 0.1923, 0.1923, 1.0]
    kd: [0.5075, 0.5075, 0.5075, 1.0]
    xkd: [1, 1, 0, 1.0]
    ks: [0.5083, 0.5083, 0.5083, 1.0]
  - name: skeleton
    type: sprite
    ns: 100
    ks: [0.6, 0.6, 0.6, 1.0]
    map_kd: Skeleton_VH.PNG
    _map_bump: Skeleton_VH_normal.PNG
  - name: brickwall
    ns: 225.000000
    type: model
    ka: [1.000000, 1.000000, 1.000000, 1.0]
    kd: [0.800000, 0.800000, 0.800000, 1.0]
    ks: [0.500000, 0.500000, 0.500000, 1.0]
    ke: [0.000000, 0.000000, 0.000000, 1.0]
    ni: 1.450000
    d: 1.000000
    illum: 2
    map_kd: brickwall.jpg
    map_bump: brickwall_normal.jpg
    reflection: 0.2
  - name: woodwall
    ns: 225.000000
    type: model
    ka: [1.000000, 1.000000, 1.000000, 1.0]
    kd: [0.800000, 0.800000, 0.800000, 1.0]
    ks: [0.500000, 0.500000, 0.500000, 1.0]
    ke: [0.000000, 0.000000, 0.000000, 1.0]
    ni: 1.450000
    d: 1.000000
    illum: 2
    map_kd: wood.png
    reflection: 0.4
  - name: giant_woodbox
    ns: 225.000000
    type: model
    ka: [1.000000, 1.000000, 1.000000, 1.0]
    kd: [0.800000, 0.800000, 0.800000, 1.0]
    ks: [0.500000, 0.500000, 0.500000, 1.0]
    ke: [0.000000, 0.000000, 0.000000, 1.0]
    ni: 1.450000
    d: 1.000000
    illum: 2
    map_kd: wood.png
    reflection: 0.1
  - name: mirror
    type: model
    ns: 225.000000
    ka: [1.000000, 1.000000, 1.000000, 1.0]
    kd: [0.800000, 0.800000, 0.800000, 1.0]
    ks: [0.500000, 0.500000, 0.500000, 1.0]
    ke: [0.000000, 0.000000, 0.000000, 1.0]
    ni: 1.450000
    d: 1.000000
    illum: 2
    map_kd: Marble White_VH.PNG
    reflection: 0.9
    refraction: 0.1
    refraction_ratio: [1.0, 1.52]
