---
name: Full
viewports:
skybox:
  shader: skybox
  material: skybox
lights: {}
root:
  id: 50733c80-df4e-47ab-9596-ccfadb1805d8
  type: origo
  pos: [200, 0, 200]
  rotation: [0, 0, 0]
  enabled: true
  controller:
    type: path
    mode: 1
    enabled: false
  xinit_script: |
    local id = node:getId()
    cmd:rotateTo(0, id, 5, 2, 0.0, 360.0, 0.0)
entities:
  - name: zero origo
    id: 65ce67c8-3efe-4b04-aaf9-fe384152c547
    type: origo
    pos: [0.0, 0.0, 0.0]
    enabled: true
    init_script: |
      local id = node:getId()
      local pos = node:getPos()
      cid = cmd:moveTo(-1, id, 5, 20, pos[1] - 20, pos[2] + 50, pos[3] + 0)
      cmd:moveTo(cid, id, 60, 20, pos[1] + 0, pos[2] + 10, pos[3] + 0)
  - name: ZERO
    parent_id: 65ce67c8-3efe-4b04-aaf9-fe384152c547
    model: water_ball
    shader: texture
    pos: [0.0, 0.0, 0.0]
    scale: 0.3
    enabled: true
    init_script: |
      local id = node:getId()
      cmd:scaleTo(-1, id, 5, 40, 4.0, 6.0, 0.2)
      cid = cmd:rotateTo(-1, id, 30, 10, 0.0, 720.0, 0.0)
      cmd:rotateTo(cid, id, 30, 10, 0.0, 720.0, 0.0)
      cmd:scaleTo(cid, id, 30, 20, 1.2, 1.2, 0.2)
  - name: Player
    model: player
    pos: [-10, 7, -20.0]
    rotation: [0, 180, 0.0]
    scale: 0.8
    render_flags:
      - --allow_normals
    camera:
      zoom: 45
      up: [0, 1, 0]
      front: [0, 0, -1]
      pos: [200, 0, 200]
      rotation: [0, 180, 0.0]
      enabled: true
    particle_generator:
      - "ParticleDefinition pd;"
      - "node->particleGenerator = std::make_unique<ParticleGenerator>(pd);"
    controller:
      type: camera
      enabled: true
    enabled: true
  - name: Directional light
    parent_id: 8712cec1-e1a3-4973-8889-533adfbbb196
    pos: [0, 0, 0]
    scale: 1.5
    model: light
    shader: light
    render_flags:
      - light
      - no_shadow
    force_material: true
    material_modifier:
      kd: [0.0, 0.7, 0.0, 1.0]
    light:
      type: directional
      world_target: [0, 0, 0]
      ambient: [0.4, 0.4, 0.4, 1.0]
      diffuse: [0.4, 0.4, 0.4, 1.0]
      specular: [0.0, 0.7, 0.0, 1.0]
      enabled: true
    controller:
      type: moving_light
      speed: 20.0
      radius: 80.0
      enabled: true
    enabled: true
  - name: Moving point light
    parent_id: 65ce67c8-3efe-4b04-aaf9-fe384152c547
    pos: [0, 9, 0]
    scale: 0.5
    model: light
    shader: light
    render_flags:
      - light
      - no_shadow
    light:
      type: point
      linear: 0.14
      quadratic: 0.07
      cutoff_angle: 12.5
      outer_cutoff_angle: 25.0
      world_target: [0, 0, 0]
      ambient: [0.4, 0.4, 0.2, 1.0]
      diffuse: [0.8, 0.8, 0.7, 1.0]
      specular: [1.0, 1.0, 0.9, 1.0]
      enabled: true
    controller:
      type: moving_light
      speed: 2.0
      radius: 10.0
      enabled: true
    repeat:
      x_count: 2
      y_count: 1
      z_count: 2
      x_step: 30
      y_step: 0
      z_step: 30
    enabled: true
  - name: Rock light
    parent_id: 7c90bc35-1a05-4755-b52a-1f8eea0bacfa
    pos: [0, 10, 0]
    scale: 0.5
    model: light
    shader: light
    render_flags:
      - light
      - no_shadow
    light:
      type: point
      linear: 0.014
      quadratic: 0.0007
      world_target: [0, 0, 0]
      ambient: [0.4, 0.4, 0.2, 1.0]
      diffuse: [0.8, 0.8, 0.7, 1.0]
      specular: [1.0, 1.0, 0.9, 1.0]
      enabled: true
    controller:
      type: moving_light
      speed: 3.0
      radius: 10.0
      enabled: true
    enabled: true
  - name: Active node
    parent_id: 65ce67c8-3efe-4b04-aaf9-fe384152c547
    model: texture_cube
    shader: texture
    pos: [0, 15, 0]
    controller:
      type: path
      mode: 1
      enabled: true
    enabled: true
  - name: Active node around rock
    id: c5c1d3e7-7d86-42d3-95e6-eed4ab54c58b
    parent_id: 7c90bc35-1a05-4755-b52a-1f8eea0bacfa
    model: texture_cube
    shader: texture
    pos: [0, -5, 0]
    controller:
      type: path
      mode: 1
      enabled: true
    enabled: true
  - name: EXAMPLE
    model: glass_ball
    shader: texture
    pos: [-1.5, 0.0, -1.5]
    rotation: [0.0, 0.0, 0.0]
    scale: 1.0
    material: glass_ball
    material_modifier:
      reflection: 0.1
      refraction: 0.9
      refraction_ratio: [1.0, 1.52]
    render_flags:
      - blend
      - render_back
    repeat:
      x_count: 2
      y_count: 1
      z_count: 2
      x_step: 3
      y_step: 0
      z_step: 3
    enabled: true
  - name: Window 1
    model: window1
    shader: texture
    pos: [5.0, 10.0, -5.0]
    rotation: [0.0, 180.0, 0.0]
    render_flags:
      - blend
      - render_back
    enabled: true
  - name: Window 2
    model: window2
    shader: texture
    pos: [7.0, 10.0, -8.0]
    rotation: [0.0, 180.0, 0.0]
    render_flags:
      - blend
      - render_back
    enabled: true
  - name: Stained windows
    model: window2
    shader: texture
    pos: [-10.0, 15.0, 10.0]
    rotation: [0.0, 180.0, 0.0]
    render_flags:
      - blend
      - render_back
    repeat:
      x_count: 10
      x_step: 2
    enabled: true
  - name: Brick wall
    model: brickwall
    shader: texture
    pos: [-5.0, 6.5, 14.0]
    render_flags:
      - render_back
    repeat:
      x_count: 3
      x_step: 4
    enabled: true
  - name: Wood wall
    model: woodwall
    shader: texture
    pos: [-3.0, 6.5, 14.0]
    material_modifier:
      reflection: 0.3
    render_flags:
      - render_back
    repeat:
      x_count: 2
      x_step: 4
    enabled: true
  - name: Big mirror 1
    model: woodwall
    shader: texture
    pos: [-65.0, 20.0, -10.0]
    rotation: [0.0, 45.0, 0.0]
    scale: 15.0
    material_modifier:
      reflection: 0.9
      refraction: 0.1
      refraction_ratio: [1.0, 1.52]
    render_flags:
      - render_back
      - mirror
    mirror_plane: [0.0, 1.0, 0.0, -1.0]
    enabled: true
  - name: Big mirror 2
    model: woodwall
    shader: texture
    pos: [65.0, 20.0, -10.0]
    rotation: [0.0, -45.0, 0.0]
    scale: 15.0
    material_modifier:
      reflection: 0.9
      refraction: 0.1
      refraction_ratio: [1.0, 1.52]
    render_flags:
      - render_back
      - mirror
    mirror_plane: [0.0, 1.0, 0.0, -1.0]
    enabled: true
  - name: Spyro
    model: spyro2
    shader: texture
    pos: [0.0, 30.0, 30.0]
    scale: 0.06
    enabled: true
  - name: Backback
    desc: TODO not showing up
    model: [backback, backback]
    shader: texture
    pos: [0.0, 5.0, 5.0]
    scale: 1.5
    enabled: false
  - name: Bunny
    model: bunny
    shader: texture
    pos: [-15.0, 10.0, 5.0]
    scale: 20.0
    material_modifier:
      reflection: 0.9
    render_flags:
      - render_back
    enabled: false
  - name: Dragon
    model: dragon
    shader: texture
    pos: [-15.0, 15.0, 0.0]
    scale: 30.0
    render_flags:
      - render_back
    enabled: false
  - name: Shuttle
    model: [shuttle, opengl_book/NasaShuttle]
    shader: texture
    pos: [20.0, 40.0, -50.0]
    scale: 20.0
    enabled: true
  - name: Sword 2
    model: sword2
    shader: texture
    pos: [0.0, 40.0, -50.0]
    scale: 1.0
    enabled: true
  - name: Teapot
    model: smooth_teapot
    shader: texture
    pos: [-5.0, 20.0, -5.0]
    scale: 1.0
    material: teapot
    material_modifier:
      reflection: 0.0
      refraction: 1.0
      refraction_ratio: [1.0, 1.52]
    render_flags:
      - render_back
    selected: false
    enabled: true
  - name: Cow
    model: texture_cow
    shader: texture
    pos: [5.0, 20.0, -5.0]
    scale: 1.0
    material: cow
    material_modifier:
      reflection: 0.5
    render_flags:
      - render_back
    selected: false
    enabled: true
  - name: Mountains
    model: texture_mountains
    shader: texture
    pos: [100.0, 0.0, -100.0]
    scale: 1.0
    enabled: true
  - name: Ball
    model: texture_ball
    shader: texture
    pos: [0.0, 8.0, 0.0]
    scale: 2.0
    enabled: true
  - name: Glass ball
    model: glass_ball
    shader: texture
    pos: [5.0, 20.0, 0.0]
    scale: 1.3
    material_modifier:
      reflection: 0.1
      refraction: 0.9
      refraction_ratio: [1.0, 1.52]
    enabled: true
  - name: Mirror ball
    model: glass_ball
    shader: texture
    pos: [0.0, 20.0, 0.0]
    scale: 1.3
    material_modifier:
      reflection: 1.0
    enabled: true
  - name: Water ball
    model: water_ball
    shader: texture
    pos: [5.0, 25.0, 0.0]
    scale: 1.3
    particle_generator:
      - ParticleDefinition pd;
      - //pd.material = Sprite::getMaterial(assets, "Skeleton_VH.PNG", "");
      - node->particleGenerator = new ParticleGenerator(assets, pd);
    material_modifier:
      reflection: 0.3
    enabled: true
  - name: Basic ball
    model: water_ball
    shader: texture
    pos: [5.0, 25.0, 5.0]
    scale: 1.3
    material: default_ball
    force_material: true
    material_modifier:
      reflection: 0.05
    enabled: true
  - name: Gold ball
    model: water_ball
    shader: texture
    pos: [5.0, 25.0, 10.0]
    scale: 1.3
    force_material: true
    material: gold_ball
    material_modifier:
      reflection: 0.05
    enabled: true
  - name: ball origo
    type: origo
    id: 82896a38-e5cf-4274-b4be-e79ac8325b65
    pos: [5.0, 25.0, 15.0]
    enabled: true
  - name: Silver ball
    model: water_ball
    shader: texture
    pos: [5.0, 25.0, 15.0]
    scale: 1.3
    force_material: true
    material: silver_ball
    material_modifier:
      reflection: 0.05
    enabled: true
  - name: Bronze ball
    parent_id: 82896a38-e5cf-4274-b4be-e79ac8325b65
    model: water_ball
    shader: texture
    pos: [0.0, 0.0, 5.0]
    scale: 1.3
    force_material: true
    material: bronze_ball
    material_modifier:
      reflection: 0.05
    enabled: true
  - name: Brickcube
    model: texture_cube
    shader: texture
    pos: [5.0, 20.0, 5.0]
    scale: 1
    enabled: true
  - name: Four cubes
    model: texture_cube_3
    shader: texture
    scale: 1
    enabled: true
    clones:
      - pos: [-5.0, 15.0, -5.0]
        init_script: |
          cmd:rotateTo(-1, node:getId(), 10, 120, 0.0, 360.0, 0.0)
      - pos: [5.0, 15.0, -5.0]
        init_script: |
          cmd:rotateTo(-1, node:getId(), 10, 120, 0.0, 2 * 360.0, 0.0)
      - pos: [-5.0, 15.0, 5.0]
        init_script: |
          cmd:rotateTo(-1, node:getId(), 10, 120, 0.0, 3 * 360.0, 0.0)
      - pos: [5.0, 15.0, 5.0]
        init_script: |
          cmd:rotateTo(-1, node:getId(), 10, 120, 0.0, 4 * 360.0, 0.0)
  - name: Cube 4
    model: texture_cube_4
    shader: texture
    pos: [-5.0, 20.0, 5.0]
    scale: 1
    selected: false
    enabled: true
  - name: Water bottom
    model: marble_plate
    shader: texture
    pos: [0.0, 3.2, -10.0]
    rotation: [90.0, 0.0, 0.0]
    scale: 30
    load_textures: false
    material_modifier:
      texture_spec:
        mode: GL_REPEAT
      tiling: 8
    render_flags:
      - no_shadow
    repeat:
      x_count: 2
      y_count: 1
      z_count: 2
      x_step: 60
      y_step: 0
      z_step: 60
    enabled: true
  - name: Water surface
    type: quad
    material: water_surface
    shader: water
    pos: [0, 5, -10]
    rotation: [270.0, 0.0, 0.0]
    scale: 30
    render_flags:
      - no_shadow
      - render_back
      - water
    repeat:
      x_count: 2
      y_count: 1
      z_count: 2
      x_step: 60
      y_step: 0
      z_step: 60
    enabled: true
  - name: Terrain grass
    type: quad
    material: terrain_grass
    shader: terrain
    pos: [-400, 0, -400]
    rotation: [270.0, 0.0, 0.0]
    scale: 100
    batch_size: 100
    render_flags:
      - no_shadow
      - --render_back
      - terrain
    repeat:
      x_count: 8
      y_count: 1
      z_count: 8
      x_step: 200
      y_step: 0
      z_step: 200
    enabled: true
  - name: Planet origo
    id: 8712cec1-e1a3-4973-8889-533adfbbb196
    type: origo
    pos: [10.0, 100.0, 100.0]
    enabled: true
  - name: Planet
    parent_id: 8712cec1-e1a3-4973-8889-533adfbbb196
    model: [planet, planet]
    shader: texture
    pos: [0, 0, 0]
    scale: 10
    material_modifier:
      fog_ratio: 0
    enabled: true
    init_script: |
      local id = node:getId()
      cmd:rotateTo(-1, id, 5, 3600, 0.0, 720.0, 0.0)
  - name: Rock origo
    id: 7c90bc35-1a05-4755-b52a-1f8eea0bacfa
    parent_id: 8712cec1-e1a3-4973-8889-533adfbbb196
    type: origo
    pos: [0.0, -50.0, 0.0]
    enabled: true
  - name: Rock
    id: 91874c8a-643c-4ae9-b90a-9712cb68f95d
    parent_id: 7c90bc35-1a05-4755-b52a-1f8eea0bacfa
    model: [rock, rock]
    shader: texture
    pos: [0.0, 0, 0.0]
    scale: 1.5
    material_modifier:
      reflection: 0.7
    enabled: true
  - name: Asteroid belt
    parent_id: 8712cec1-e1a3-4973-8889-533adfbbb196
    model: [rock, rock]
    instanced: true
    shader: texture
    pos: [0, 0, 0]
    controller:
      type: asteroid_belt
      count: 1000
      enabled: true
    enabled: true
  - name: Skeleton army
    type: sprite
    shader: texture
    pos: [15, 6.5, 20.0]
    material: skeleton
    batch_size: 1000
    render_flags:
      - alpha
      - render_back
    scale: [1.5, 3, 1]
    repeat:
      x_count: 10
      z_count: 101
      x_step: -4
      z_step: 0.2
    enabled: true
    init_script: |
      local id = node:getId()
      local pos = node:getPos()

      cid = cmd:moveTo(-1, id, 5, 10, pos[1] + 25 - math.random(100), pos[2], pos[3] + 25 - math.random(100))
      cmd:cancel(-1, 7, 0, cid)

      cid = cmd:moveTo(cid, id, 0, 10, pos[1] + 25 - math.random(100), pos[2], pos[3] + 25 - math.random(100))
      cmd:cancel(-1, 0, 0, cid)
      cid = cmd:moveTo(cid, id, 0, 5, pos[1] + 25 - math.random(50), pos[2], pos[3] + 25 - math.random(50))
      cid = cmd:moveTo(cid, id, 0, 5, pos[1] + 10 - math.random(20), pos[2], pos[3] + 10 - math.random(20))
      cid = cmd:moveTo(cid, id, 0, 3, pos[1] + 5 - math.random(10), pos[2], pos[3] + 5 - math.random(10))
      cid = cmd:moveTo(cid, id, 0, 2, pos[1], pos[2], pos[3])
  - name: Skeleton single
    xid: fb7ba424-f219-4c12-a00f-703b9ecebbbf
    type: sprite
    shader: texture
    pos: [15, 6.5, 20.0]
    material: skeleton
    batch_size: 1000
    render_flags:
      - alpha
      - render_back
    scale: [1.5, 3, 1]
    enabled: false
  - name: Giant wooden box
    id: e264f27f-d949-4504-b862-583213484d7c
    model: woodwall
    shader: texture
    clone_position: [0, 40, 0]
    render_flags:
      - render_back
      - no_shadow
    scale: [100, 100, 100]
    enabled: true
    clones:
      - pos: [0.0, 100.0, 0.0]
        rot: [270, 0, 0]
        id: 9da42971-4809-480b-98b6-ed238b978ed2
      - pos: [0.0, -100.0, .0]
        rot: [90, 0, 0]
      - pos: [100.0, 0.0, 0.0]
        rot: [0, 90, 0]
      - pos: [-100.0, 0.0, 0.0]
        rot: [0, 270, 0]
      - pos: [0.0, 0.0, 100.0]
        rot: [0, 0, 0]
      - pos: [0.0, 0.0, -100.0]
        rot: [0, 180, 0]
materials:
  - name: skybox
    type: skybox
    asset: skybox
  - name: default
    ns: 100.0
    ka: [0.3, 0.3, 0.0, 1.0]
    kd: [0.8, 0.8, 0.0, 1.0]
    ks: [0.9, 0.9, 0.0, 1.0]
  - name: teapot
    ns: 100.0
    ka: [0.3, 0.3, 0.0, 1.0]
    kd: [0.578, 0.578, 0.168, 1.0]
    ks: [0.9, 0.9, 0.0, 1.0]
  - name: cow
    ns: 100.0
    ka: [0.3, 0.3, 0.0, 1.0]
    kd: [0.160, 0.578, 0.168, 1.0]
    ks: [0.9, 0.9, 0.0, 1.0]
  - name: default_ball
    ns: 100.0
    ka: [0.3, 0.3, 0.0, 1.0]
    kd: [0.8, 0.8, 0.0, 1.0]
    ks: [0.9, 0.9, 0.0, 1.0]
  - name: gold_ball
    ns: 51.2
    ka: [0.2473, 0.1995, 0.0745, 1.0]
    kd: [0.7516, 0.6065, 0.2265, 1.0]
    ks: [0.6283, 0.5559, 0.3661, 1.0]
  - name: silver_ball
    ns: 51.2
    ka: [0.1923, 0.1923, 0.1923, 1.0]
    kd: [0.5075, 0.5075, 0.5075, 1.0]
    ks: [0.5083, 0.5083, 0.5083, 1.0]
  - name: bronze_ball
    ns: 25.6
    ka: [0.2125, 0.1275, 0.0540, 1.0]
    kd: [0.7140, 0.4284, 0.1814, 1.0]
    ks: [0.3936, 0.2719, 0.1667, 1.0]
  - name: copper
    ns: 225.000000
    ka: [1.000000, 1.000000, 1.000000]
    kd: [0.800000, 0.800000, 0.800000]
    ks: [0.500000, 0.500000, 0.500000]
    ke: [0.000000, 0.000000, 0.000000]
    ni: 1.450000
    d: 1.000000
    illum: 2
    map_kd: Dirt_vh.png
  - name: mirror_todo
    ns: 225.000000
    ka: [1.000000, 1.000000, 1.000000, 1.0]
    kd: [0.800000, 0.800000, 0.800000, 1.0]
    ks: [0.500000, 0.500000, 0.500000, 1.0]
    ke: [0.000000, 0.000000, 0.000000, 1.0]
    ni: 1.450000
    d: 1.000000
    illum: 2
    map_kd: wood.png
    reflection: 0.1
    refraction: 0.9
    refraction_ratio: [1.0, 1.52]
  - name: default_glass_ball_todo
    ns: 100.0
    ka: [0.3, 0.3, 0.0, 1.0]
    kd: [0.8, 0.8, 0.0, 1.0]
    ks: [0.9, 0.9, 0.0, 1.0]
    reflection: 0.1
    refraction: 0.9
    refraction_ratio: [1.0, 1.52]
  - name: wood_wall_todo
    ns: 225.000000
    ka: [1.000000, 1.000000, 1.000000, 1.0]
    kd: [0.800000, 0.800000, 0.800000, 1.0]
    ks: [0.500000, 0.500000, 0.500000, 1.0]
    ke: [0.000000, 0.000000, 0.000000, 1.0]
    ni: 1.450000
    d: 1.000000
    illum: 2
    map_kd: wood.png
    reflection: 0.3
  - name: skeleton
    type: sprite
    ns: 100
    ks: [0.6, 0.6, 0.6, 1.0]
    map_kd: Skeleton_VH.PNG
    _map_bump: Skeleton_VH_normal.PNG
  - name: water_surface
    type: texture
    ns: 150
    ks: [0.2, 0.2, 0.5, 1.0]
    kd: [0.0, 0.1, 0.8, 1.0]
    map_bump: waterNormalMap.png
    map_dudv: waterDUDV.png
    tiling: 2
    texture_spec:
      mode: GL_REPEAT
      _pattern: 1
  - name: terrain_grass
    type: texture
    ns: 50
    ks: [0.6, 0.6, 0.6, 1.0]
    map_kd: Grass Dark_VH.PNG
    map_bump: waterNormalMap.png
    tiling: 2
    texture_spec:
      mode: GL_REPEAT
