---
name: Full
viewports:
skybox:
  shader: skybox
  material: skybox
lights: {}
root:
  id: 50733c80-df4e-47ab-9596-ccfadb1805d8
  type: origo
  pos: [200, 0, 200]
  rotation: [0, 0, 0]
  enabled: true
  controller:
    type: path
    mode: 1
    enabled: false
entities:
  - name: Origo
    type: origo
    pos: [0, 0, -5]
    camera:
      zoom: 45
      up: [0, 1, 0]
      front: [0, 0, -1]
      pos: [200, 0, 190]
      rotation: [0, 180, 0.0]
      enabled: true
    controller:
      type: camera
      enabled: true
    enabled: true
  - name: Silver ball
    model: water_ball
    shader: texture
    pos: [0, 0, 0]
    scale: 1.3
    force_material: true
    material: silver_ball
    material_modifier:
      reflection: 0.05
    enabled: true
  - name: Four cubes
    model: texture_cube_3
    shader: texture
    scale: 1
    enabled: true
    clones:
      - pos: [-5.0, 15.0, -5.0]
      - pos: [5.0, 15.0, -5.0]
      - pos: [-5.0, 15.0, 5.0]
      - pos: [5.0, 15.0, 5.0]
  - name: Skeleton army
    type: sprite
    shader: sprite
    pos: [15, 6.5, 20.0]
    material: skeleton
    batch_size: 1000
    render_flags:
      alpha: true
      render_back: true
    scale: [1.5, 3, 1]
    repeat:
      x_count: 10
      z_count: 101
      x_step: -4
      z_step: 1.5
    enabled: false
  - name: Cube map 1
    type: origo
    pos: [0.0, -3.0, 0.0]
    render_flags:
      cube_map: true
    enabled: true
  - name: Glass ball
    model: glass_ball
    shader: texture
    pos: [5.0, 20.0, 0.0]
    scale: 1.3
    material_modifier:
      reflection: 0.1
      refraction: 0.9
      refraction_ratio: [1.0, 1.52]
    enabled: true
materials:
  - name: skybox
    type: skybox
    asset: skybox
  - name: silver_ball
    ns: 51.2
    ka: [0.1923, 0.1923, 0.1923, 1.0]
    _kd: [0.5075, 0.5075, 0.5075, 1.0]
    kd: [1, 1, 0, 1.0]
    ks: [0.5083, 0.5083, 0.5083, 1.0]
  - name: skeleton
    type: sprite
    ns: 100
    ks: [0.6, 0.6, 0.6, 1.0]
    map_kd: Skeleton_VH.PNG
    _map_bump: Skeleton_VH_normal.PNG
