---
name: Full
viewports:
skybox:
  shader: skybox
  material: skybox
lights: {}
entities:
  - name: Player
    id: db3e098e-9ed5-4741-b986-16cfc1b2fe9b
    model: player
    pos: [-10, 7, -20.0]
    rotation: [0, 180, 0.0]
    scale: 0.8
    render_flags:
      - --allow_normals
    camera:
      zoom: 45
      up: [0, 1, 0]
      front: [0, 0, -1]
      pos: [0, 0, 0]
      rotation: [0, 180, 0.0]
      enabled: true
    particle_generator:
      - "ParticleDefinition pd;"
      - "node->particleGenerator = std::make_unique<ParticleGenerator>(pd);"
    controller:
      type: camera
      enabled: true
    enabled: true
  - name: Directional light
    light:
      type: directional
  - name: Moving point light
    light:
      type: point
  - name: EXAMPLE
    id: 68f300d2-34b0-4fb0-aa4e-6690e091d63c
    model: glass_ball
    shader: texture
    pos: [0.0, 0.0, 0.0]
    rotation: [0.0, 0.0, 0.0]
    scale: 1.0
    material: glass_ball
    material_modifier:
      reflection: 0.1
      refraction: 0.9
      refraction_ratio: [1.0, 1.52]
    render_flags:
      - blend
      - render_back
    repeat:
      x_count: 2
      y_count: 1
      z_count: 2
      x_step: 2
      y_step: 2
      z_step: 2
    enabled: true
  - name: ZERO
    id: 65ce67c8-3efe-4b04-aaf9-fe384152c547
    model: water_ball
    shader: texture
    pos: [0.0, 0.0, 0.0]
    scale: 0.3
    enabled: true
  - name: Window 1
    id: 348ec505-240a-4d86-9d97-2a62eb0eefaf
    model: window1
    shader: texture
    pos: [5.0, 10.0, -5.0]
    rotation: [0.0, 180.0, 0.0]
    shader_definitions:
      - USE_ALPHA
    render_flags:
      - blend
      - render_back
    enabled: true
  - name: Window 2
    id: 33550e8b-8540-4114-b73d-0322444e6453
    model: window2
    shader: texture
    pos: [7.0, 10.0, -8.0]
    rotation: [0.0, 180.0, 0.0]
    shader_definitions:
      - USE_ALPHA
    render_flags:
      - blend
      - render_back
    enabled: true
  - name: Stained windows
    id: 21ed5ac7-073c-4ae2-8bd0-d721f92d2b9b
    model: window2
    shader: texture
    pos: [-10.0, 15.0, 10.0]
    rotation: [0.0, 180.0, 0.0]
    shader_definitions:
      - USE_ALPHA
    render_flags:
      - blend
      - render_back
    repeat:
      x_count: 10
      x_step: 2
    enabled: true
  - name: Brick wall
    id: 43e08833-6167-40cd-b472-96d29cd8a08c
    model: brickwall
    shader: texture
    pos: [-5.0, 6.5, 14.0]
    render_flags:
      - render_back
    repeat:
      x_count: 3
      x_step: 4
    enabled: true
  - name: Wood wall
    id: 43e417b5-9697-4821-9abb-84dbad3adfce
    model: woodwall
    shader: texture
    pos: [-3.0, 6.5, 14.0]
    material_modifier:
      reflection: 0.3
    render_flags:
      - render_back
    repeat:
      x_count: 2
      x_step: 4
    enabled: true
  - name: Big mirror 1
    id: 640a76d4-fa07-4407-8204-009c9bc3ff29
    model: woodwall
    shader: texture
    pos: [-65.0, 20.0, -10.0]
    rotation: [0.0, 45.0, 0.0]
    scale: 15.0
    material_modifier:
      reflection: 0.9
      refraction: 0.1
      refraction_ratio: [1.0, 1.52]
    render_flags:
      - render_back
      - mirror
    mirror_plane: [0.0, 1.0, 0.0, -1.0]
    enabled: true
  - name: Big mirror 2
    id: d3ceb264-e4dc-4063-9f9d-6c3734e4f616
    model: woodwall
    shader: texture
    pos: [65.0, 20.0, -10.0]
    rotation: [0.0, -45.0, 0.0]
    scale: 15.0
    material_modifier:
      reflection: 0.9
      refraction: 0.1
      refraction_ratio: [1.0, 1.52]
    render_flags:
      - render_back
      - mirror
    mirror_plane: [0.0, 1.0, 0.0, -1.0]
    enabled: true
  - name: Spyro
    id: d96d4ca9-26c7-48c8-8459-f31b8270b5e2
    model: spyro2
    shader: texture
    pos: [0.0, 30.0, 30.0]
    scale: 0.06
    enabled: true
  - name: Backback
    desc: TODO not showing up
    id: 0bdeb80d-0469-468f-95b9-e9928266d93a
    model: [backback, backback]
    shader: texture
    pos: [0.0, 5.0, 5.0]
    scale: 1.5
    enabled: false
  - name: Bunny
    id: 7deb60bf-cdc6-497a-b296-32c0a5a9a5aa
    model: bunny
    shader: texture
    pos: [-15.0, 10.0, 5.0]
    scale: 20.0
    material_modifier:
      reflection: 0.9
    render_flags:
      - render_back
    enabled: false
  - name: Dragon
    id: cab47b14-9a9d-4db2-96fd-7b872f79e096
    model: dragon
    shader: texture
    pos: [-15.0, 15.0, 0.0]
    scale: 30.0
    render_flags:
      - render_back
    enabled: false
  - name: Shuttle
    id: 9a2ba708-dc8b-4e5e-902c-0375ce432a1f
    model: [shuttle, opengl_book/NasaShuttle]
    shader: texture
    pos: [20.0, 40.0, -50.0]
    scale: 20.0
    enabled: true
  - name: Sword 2
    id: 96e6e2b2-6110-45cc-aef3-19ba321a8443
    model: sword2
    shader: texture
    pos: [0.0, 40.0, -50.0]
    scale: 1.0
    enabled: true
  - name: Teapot
    id: 53f4bd23-8f9f-4cc4-b4ce-7f71d6484ce4
    model: smooth_teapot
    shader: texture
    pos: [-5.0, 20.0, -5.0]
    scale: 1.0
    material: teapot
    material_modifier:
      reflection: 0.0
      refraction: 1.0
      refraction_ratio: [1.0, 1.52]
    render_flags:
      - render_back
    selected: false
    enabled: true
  - name: Cow
    id: 03804c4f-ec37-445f-9fbd-675c667a704a
    model: texture_cow
    shader: texture
    pos: [5.0, 20.0, -5.0]
    scale: 1.0
    material: cow
    material_modifier:
      reflection: 0.5
    render_flags:
      - render_back
    selected: false
    enabled: true
  - name: Mountains
    id: 63ca20c5-dce1-4400-8968-6484cb4af8ca
    model: texture_mountains
    shader: texture
    pos: [100.0, 0.0, -100.0]
    scale: 1.0
    enabled: true
  - name: Ball
    id: 378a3ab8-5923-449b-9cb3-fc8a43ad01ff
    model: texture_ball
    shader: texture
    pos: [0.0, 8.0, 0.0]
    scale: 2.0
    enabled: true
  - name: Glass ball
    id: 765cc20c-f0ec-4beb-8ca0-c8b8e61fe867
    model: glass_ball
    shader: texture
    pos: [5.0, 20.0, 0.0]
    scale: 1.3
    material_modifier:
      reflection: 0.1
      refraction: 0.9
      refraction_ratio: [1.0, 1.52]
    enabled: true
  - name: Mirror ball
    id: 7dba2d65-e7c2-4e93-8e99-b2347733becf
    model: glass_ball
    shader: texture
    pos: [0.0, 20.0, 0.0]
    scale: 1.3
    material_modifier:
      reflection: 1.0
    enabled: true
  - name: Water ball
    id: 6d104f0b-d706-4919-9a7a-732e3c1f5749
    model: water_ball
    shader: texture
    pos: [5.0, 25.0, 0.0]
    scale: 1.3
    particle_generator:
      - ParticleDefinition pd;
      - //pd.material = Sprite::getMaterial(assets, "Skeleton_VH.PNG", "");
      - node->particleGenerator = new ParticleGenerator(assets, pd);
    material_modifier:
      reflection: 0.3
    enabled: true
  - name: Basic ball
    id: 3fa60b1c-db58-4c0d-b96a-56672a1a8ca9
    model: water_ball
    shader: texture
    pos: [5.0, 25.0, 5.0]
    scale: 1.3
    material: default_ball
    override_material: true
    material_modifier:
      reflection: 0.05
    enabled: true
  - name: Gold ball
    id: 056709c1-e452-4069-8482-fd56a578ebfd
    model: water_ball
    shader: texture
    pos: [5.0, 25.0, 10.0]
    scale: 1.3
    override_material: true
    material: gold_ball
    material_modifier:
      reflection: 0.05
    enabled: true
  - name: Silver ball
    id: 82896a38-e5cf-4274-b4be-e79ac8325b65
    model: water_ball
    shader: texture
    pos: [5.0, 25.0, 15.0]
    scale: 1.3
    override_material: true
    material: silver_ball
    material_modifier:
      reflection: 0.05
    enabled: true
  - name: Bronze ball
    id: 3254214e-feff-4e12-8099-0da57eae709a
    parent_id: 82896a38-e5cf-4274-b4be-e79ac8325b65
    model: water_ball
    shader: texture
    pos: [0.0, 0.0, 5.0]
    scale: 1.3
    override_material: true
    material: bronze_ball
    material_modifier:
      reflection: 0.05
    enabled: true
  - name: Brickcube
    id: 06106e7a-c538-4c7f-ae4e-4ab7a5012a94
    model: texture_cube
    shader: texture
    pos: [5.0, 20.0, 5.0]
    scale: 1
    enabled: true
  - name: Four cubes
    id: 6c4675b6-3716-4c9e-bb4b-32e49de7349c
    model: texture_cube_3
    shader: texture
    positions:
      - [-5.0, 15.0, -5.0]
      - [5.0, 15.0, -5.0]
      - [-5.0, 15.0, 5.0]
      - [5.0, 15.0, 5.0]
    scale: 1
    enabled: true
  - name: Cube 4
    id: c732f488-903e-40d0-8b24-389374d89a63
    model: texture_cube_4
    shader: texture
    pos: [-5.0, 20.0, 5.0]
    scale: 1
    selected: false
    enabled: true
  - name: Water bottom
    id: 0f93cffa-a1e9-4040-885f-3075bbcca722
    model: marble_plate
    shader: texture
    pos: [0.0, 3.2, -10.0]
    rotation: [90.0, 0.0, 0.0]
    scale: 30
    load_textures: false
    material_modifier:
      texture_spec:
        mode: GL_REPEAT
      tiling: 8
    render_flags:
      - no_shadow
    repeat:
      x_count: 2
      y_count: 1
      z_count: 2
      x_step: 60
      y_step: 0
      z_step: 60
    enabled: true
  - name: Water surface
    id: 7207c9ea-868d-4fbf-b511-73407aacf31f
    type: quad
    material: water_surface
    shader: water
    pos: [0, 5, -10]
    rotation: [270.0, 0.0, 0.0]
    scale: 30
    render_flags:
      - no_shadow
      - render_back
      - water
    repeat:
      x_count: 2
      y_count: 1
      z_count: 2
      x_step: 60
      y_step: 0
      z_step: 60
    enabled: true
  - name: Terrain grass
    id: 765f5288-21ec-4234-b7cd-6cdba4087e97
    type: quad
    material: terrain_grass
    shader: terrain
    pos: [-400, 0, -400]
    rotation: [270.0, 0.0, 0.0]
    scale: 100
    batch_size: 100
    render_flags:
      - no_shadow
      - --render_back
      - terrain
    repeat:
      x_count: 8
      y_count: 1
      z_count: 8
      x_step: 200
      y_step: 0
      z_step: 200
    enabled: true
  - name: Planet
    id: 8712cec1-e1a3-4973-8889-533adfbbb196
    model: [planet, planet]
    shader: texture
    pos: [10.0, 100.0, 100.0]
    scale: 10
    material_modifier:
      fog_ratio: 0
    enabled: true
  - name: Rock
    id: 7c90bc35-1a05-4755-b52a-1f8eea0bacfa
    parent_id: 8712cec1-e1a3-4973-8889-533adfbbb196
    model: [rock, rock]
    shader: texture
    pos: [0.0, -50.0, 0.0]
    scale: 1
    material_modifier:
      reflection: 0.7
    enabled: true
  - name: Skeleton army
    id: fb7ba424-f219-4c12-a00f-703b9ecebbbf
    type: sprite
    shader: texture
    pos: [15, 6.5, 20.0]
    material: skeleton
    batch_size: 1000
    shader_definitions:
      - USE_ALPHA
    render_flags:
      - alpha
      - render_back
    scale: [1.5, 3, 1]
    repeat:
      x_count: 10
      z_count: 101
      x_step: -4
      z_step: 0.2
    enabled: true
materials:
  - name: skybox
    type: skybox
    asset: skybox
  - name: default
    ns: 100.0
    ka: [0.3, 0.3, 0.0, 1.0]
    kd: [0.8, 0.8, 0.0, 1.0]
    ks: [0.9, 0.9, 0.0, 1.0]
  - name: teapot
    ns: 100.0
    ka: [0.3, 0.3, 0.0, 1.0]
    kd: [0.578, 0.578, 0.168, 1.0]
    ks: [0.9, 0.9, 0.0, 1.0]
  - name: cow
    ns: 100.0
    ka: [0.3, 0.3, 0.0, 1.0]
    kd: [0.160, 0.578, 0.168, 1.0]
    ks: [0.9, 0.9, 0.0, 1.0]
  - name: default_ball
    ns: 100.0
    ka: [0.3, 0.3, 0.0, 1.0]
    kd: [0.8, 0.8, 0.0, 1.0]
    ks: [0.9, 0.9, 0.0, 1.0]
  - name: gold_ball
    ns: 51.2
    ka: [0.2473, 0.1995, 0.0745, 1.0]
    kd: [0.7516, 0.6065, 0.2265, 1.0]
    ks: [0.6283, 0.5559, 0.3661, 1.0]
  - name: silver_ball
    ns: 51.2
    ka: [0.1923, 0.1923, 0.1923, 1.0]
    kd: [0.5075, 0.5075, 0.5075, 1.0]
    ks: [0.5083, 0.5083, 0.5083, 1.0]
  - name: bronze_ball
    ns: 25.6
    ka: [0.2125, 0.1275, 0.0540, 1.0]
    kd: [0.7140, 0.4284, 0.1814, 1.0]
    ks: [0.3936, 0.2719, 0.1667, 1.0]
  - name: copper
    ns: 225.000000
    ka: [1.000000, 1.000000, 1.000000]
    kd: [0.800000, 0.800000, 0.800000]
    ks: [0.500000, 0.500000, 0.500000]
    ke: [0.000000, 0.000000, 0.000000]
    ni: 1.450000
    d: 1.000000
    illum: 2
    map_kd: Dirt_vh.png
  - name: mirror_todo
    ns: 225.000000
    ka: [1.000000, 1.000000, 1.000000, 1.0]
    kd: [0.800000, 0.800000, 0.800000, 1.0]
    ks: [0.500000, 0.500000, 0.500000, 1.0]
    ke: [0.000000, 0.000000, 0.000000, 1.0]
    ni: 1.450000
    d: 1.000000
    illum: 2
    map_kd: wood.png
    reflection: 0.1
    refraction: 0.9
    refraction_ratio: [1.0, 1.52]
  - name: default_glass_ball_todo
    ns: 100.0
    ka: [0.3, 0.3, 0.0, 1.0]
    kd: [0.8, 0.8, 0.0, 1.0]
    ks: [0.9, 0.9, 0.0, 1.0]
    reflection: 0.1
    refraction: 0.9
    refraction_ratio: [1.0, 1.52]
  - name: wood_wall_todo
    ns: 225.000000
    ka: [1.000000, 1.000000, 1.000000, 1.0]
    kd: [0.800000, 0.800000, 0.800000, 1.0]
    ks: [0.500000, 0.500000, 0.500000, 1.0]
    ke: [0.000000, 0.000000, 0.000000, 1.0]
    ni: 1.450000
    d: 1.000000
    illum: 2
    map_kd: wood.png
    reflection: 0.3
  - name: skeleton
    type: sprite
    ns: 100
    ks: [0.6, 0.6, 0.6, 1.0]
    map_kd: Skeleton_VH.PNG
    _map_bump: Skeleton_VH_normal.PNG
  - name: water_surface
    type: texture
    ns: 150
    ks: [0.2, 0.2, 0.5, 1.0]
    kd: [0.0, 0.1, 0.8, 1.0]
    map_bump: waterNormalMap.png
    map_dudv: waterDUDV.png
    tiling: 2
    texture_spec:
      mode: GL_REPEAT
      _pattern: 1
  - name: terrain_grass
    type: texture
    ns: 50
    ks: [0.6, 0.6, 0.6, 1.0]
    map_kd: Grass Dark_VH.PNG
    map_bump: waterNormalMap.png
    tiling: 2
    texture_spec:
      mode: GL_REPEAT
